name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile sources
        run: |
          mkdir -p build/classes
          javac -d build/classes $(git ls-files '*.java')

      - name: Write manifest
        run: |
          mkdir -p build
          cat <<'EOM' > build/MANIFEST.MF
          Main-Class: Game

          EOM

      - name: Package jar
        run: |
          jar --create --manifest build/MANIFEST.MF --file build/coup-${{ github.ref_name }}.jar -C build/classes .

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: coup-${{ github.ref_name }}.jar
          path: build/coup-${{ github.ref_name }}.jar

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/coup-${{ github.ref_name }}.jar
          asset_name: coup-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
